/* The following code was generated by JFlex 1.4.3 on 06/10/15 15:53 */

package claims.bold.intellij.avro.idl;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static claims.bold.intellij.avro.idl.psi.AvroIdlTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 06/10/15 15:53 from the specification file
 * <tt>/home/abigail/code/intellij-avro/src/claims/bold/intellij/avro/idl/_AvroIdlLexer.flex</tt>
 */
public class _AvroIdlLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\10\1\3\1\2\1\0\1\3\1\1\16\10\4\0\1\3\1\0"+
    "\1\16\1\0\1\7\2\0\1\0\1\27\1\30\1\5\1\24\1\36"+
    "\1\17\1\22\1\4\1\20\11\21\1\0\1\37\1\33\1\40\1\34"+
    "\1\0\1\35\4\12\1\23\25\12\1\31\1\14\1\32\1\11\1\12"+
    "\1\6\1\50\1\64\1\45\1\54\1\52\1\57\1\63\1\56\1\55"+
    "\2\7\1\46\1\51\1\47\1\43\1\41\1\7\1\42\1\53\1\44"+
    "\1\15\1\7\1\61\1\60\1\62\1\7\1\25\1\0\1\26\1\0"+
    "\41\10\2\0\4\7\4\0\1\7\2\0\1\10\7\0\1\7\4\0"+
    "\1\7\5\0\27\7\1\0\37\7\1\0\u01ca\7\4\0\14\7\16\0"+
    "\5\7\7\0\1\7\1\0\1\7\21\0\160\10\5\7\1\0\2\7"+
    "\2\0\4\7\10\0\1\7\1\0\3\7\1\0\1\7\1\0\24\7"+
    "\1\0\123\7\1\0\213\7\1\0\5\10\2\0\236\7\11\0\46\7"+
    "\2\0\1\7\7\0\47\7\11\0\55\10\1\0\1\10\1\0\2\10"+
    "\1\0\2\10\1\0\1\10\10\0\33\7\5\0\3\7\15\0\4\10"+
    "\7\0\1\7\4\0\13\10\5\0\53\7\25\10\12\13\4\0\2\7"+
    "\1\10\143\7\1\0\1\7\10\10\1\0\6\10\2\7\2\10\1\0"+
    "\4\10\2\7\12\13\3\7\2\0\1\7\17\0\1\10\1\7\1\10"+
    "\36\7\33\10\2\0\131\7\13\10\1\7\16\0\12\13\41\7\11\10"+
    "\2\7\4\0\1\7\5\0\26\7\4\10\1\7\11\10\1\7\3\10"+
    "\1\7\5\10\22\0\31\7\3\10\244\0\4\10\66\7\3\10\1\7"+
    "\22\10\1\7\7\10\12\7\2\10\2\0\12\13\1\0\7\7\1\0"+
    "\7\7\1\0\3\10\1\0\10\7\2\0\2\7\2\0\26\7\1\0"+
    "\7\7\1\0\1\7\3\0\4\7\2\0\1\10\1\7\7\10\2\0"+
    "\2\10\2\0\3\10\1\7\10\0\1\10\4\0\2\7\1\0\3\7"+
    "\2\10\2\0\12\13\4\7\7\0\1\7\5\0\3\10\1\0\6\7"+
    "\4\0\2\7\2\0\26\7\1\0\7\7\1\0\2\7\1\0\2\7"+
    "\1\0\2\7\2\0\1\10\1\0\5\10\4\0\2\10\2\0\3\10"+
    "\3\0\1\10\7\0\4\7\1\0\1\7\7\0\12\13\2\10\3\7"+
    "\1\10\13\0\3\10\1\0\11\7\1\0\3\7\1\0\26\7\1\0"+
    "\7\7\1\0\2\7\1\0\5\7\2\0\1\10\1\7\10\10\1\0"+
    "\3\10\1\0\3\10\2\0\1\7\17\0\2\7\2\10\2\0\12\13"+
    "\1\0\1\7\17\0\3\10\1\0\10\7\2\0\2\7\2\0\26\7"+
    "\1\0\7\7\1\0\2\7\1\0\5\7\2\0\1\10\1\7\7\10"+
    "\2\0\2\10\2\0\3\10\10\0\2\10\4\0\2\7\1\0\3\7"+
    "\2\10\2\0\12\13\1\0\1\7\20\0\1\10\1\7\1\0\6\7"+
    "\3\0\3\7\1\0\4\7\3\0\2\7\1\0\1\7\1\0\2\7"+
    "\3\0\2\7\3\0\3\7\3\0\14\7\4\0\5\10\3\0\3\10"+
    "\1\0\4\10\2\0\1\7\6\0\1\10\16\0\12\13\11\0\1\7"+
    "\7\0\3\10\1\0\10\7\1\0\3\7\1\0\27\7\1\0\12\7"+
    "\1\0\5\7\3\0\1\7\7\10\1\0\3\10\1\0\4\10\7\0"+
    "\2\10\1\0\2\7\6\0\2\7\2\10\2\0\12\13\22\0\2\10"+
    "\1\0\10\7\1\0\3\7\1\0\27\7\1\0\12\7\1\0\5\7"+
    "\2\0\1\10\1\7\7\10\1\0\3\10\1\0\4\10\7\0\2\10"+
    "\7\0\1\7\1\0\2\7\2\10\2\0\12\13\1\0\2\7\17\0"+
    "\2\10\1\0\10\7\1\0\3\7\1\0\51\7\2\0\1\7\7\10"+
    "\1\0\3\10\1\0\4\10\1\7\10\0\1\10\10\0\2\7\2\10"+
    "\2\0\12\13\12\0\6\7\2\0\2\10\1\0\22\7\3\0\30\7"+
    "\1\0\11\7\1\0\1\7\2\0\7\7\3\0\1\10\4\0\6\10"+
    "\1\0\1\10\1\0\10\10\22\0\2\10\15\0\60\7\1\10\2\7"+
    "\7\10\4\0\10\7\10\10\1\0\12\13\47\0\2\7\1\0\1\7"+
    "\2\0\2\7\1\0\1\7\2\0\1\7\6\0\4\7\1\0\7\7"+
    "\1\0\3\7\1\0\1\7\1\0\1\7\2\0\2\7\1\0\4\7"+
    "\1\10\2\7\6\10\1\0\2\10\1\7\2\0\5\7\1\0\1\7"+
    "\1\0\6\10\2\0\12\13\2\0\2\7\42\0\1\7\27\0\2\10"+
    "\6\0\12\13\13\0\1\10\1\0\1\10\1\0\1\10\4\0\2\10"+
    "\10\7\1\0\44\7\4\0\24\10\1\0\2\10\5\7\13\10\1\0"+
    "\44\10\11\0\1\10\71\0\53\7\24\10\1\7\12\13\6\0\6\7"+
    "\4\10\4\7\3\10\1\7\3\10\2\7\7\10\3\7\4\10\15\7"+
    "\14\10\1\7\1\10\12\13\4\10\2\0\46\7\12\0\53\7\1\0"+
    "\1\7\3\0\u0149\7\1\0\4\7\2\0\7\7\1\0\1\7\1\0"+
    "\4\7\2\0\51\7\1\0\4\7\2\0\41\7\1\0\4\7\2\0"+
    "\7\7\1\0\1\7\1\0\4\7\2\0\17\7\1\0\71\7\1\0"+
    "\4\7\2\0\103\7\2\0\3\10\40\0\20\7\20\0\125\7\14\0"+
    "\u026c\7\2\0\21\7\1\0\32\7\5\0\113\7\3\0\3\7\17\0"+
    "\15\7\1\0\4\7\3\10\13\0\22\7\3\10\13\0\22\7\2\10"+
    "\14\0\15\7\1\0\3\7\1\0\2\10\14\0\64\7\40\10\3\0"+
    "\1\7\3\0\2\7\1\10\2\0\12\13\41\0\3\10\2\0\12\13"+
    "\6\0\130\7\10\0\51\7\1\10\1\7\5\0\106\7\12\0\35\7"+
    "\3\0\14\10\4\0\14\10\12\0\12\13\36\7\2\0\5\7\13\0"+
    "\54\7\4\0\21\10\7\7\2\10\6\0\12\13\46\0\27\7\5\10"+
    "\4\0\65\7\12\10\1\0\35\10\2\0\1\10\12\13\6\0\12\13"+
    "\15\0\1\7\130\0\5\10\57\7\21\10\7\7\4\0\12\13\21\0"+
    "\11\10\14\0\3\10\36\7\12\10\3\0\2\7\12\13\6\0\46\7"+
    "\16\10\14\0\44\7\24\10\10\0\12\13\3\0\3\7\12\13\44\7"+
    "\122\0\3\10\1\0\25\10\4\7\1\10\4\7\1\10\15\0\300\7"+
    "\47\10\25\0\4\10\u0116\7\2\0\6\7\2\0\46\7\2\0\6\7"+
    "\2\0\10\7\1\0\1\7\1\0\1\7\1\0\1\7\1\0\37\7"+
    "\2\0\65\7\1\0\7\7\1\0\1\7\3\0\3\7\1\0\7\7"+
    "\3\0\4\7\2\0\6\7\4\0\15\7\5\0\3\7\1\0\7\7"+
    "\16\0\5\10\32\0\5\10\20\0\2\7\23\0\1\7\13\0\5\10"+
    "\5\0\6\10\1\0\1\7\15\0\1\7\20\0\15\7\3\0\32\7"+
    "\26\0\15\10\4\0\1\10\3\0\14\10\21\0\1\7\4\0\1\7"+
    "\2\0\12\7\1\0\1\7\3\0\5\7\6\0\1\7\1\0\1\7"+
    "\1\0\1\7\1\0\4\7\1\0\13\7\2\0\4\7\5\0\5\7"+
    "\4\0\1\7\21\0\51\7\u0a77\0\57\7\1\0\57\7\1\0\205\7"+
    "\6\0\4\7\3\10\16\0\46\7\12\0\66\7\11\0\1\7\17\0"+
    "\1\10\27\7\11\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7"+
    "\1\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0\40\10"+
    "\57\0\1\7\u01d5\0\3\7\31\0\11\7\6\10\1\0\5\7\2\0"+
    "\5\7\4\0\126\7\2\0\2\10\2\0\3\7\1\0\132\7\1\0"+
    "\4\7\5\0\51\7\3\0\136\7\21\0\33\7\65\0\20\7\u0200\0"+
    "\u19b6\7\112\0\u51cc\7\64\0\u048d\7\103\0\56\7\2\0\u010d\7\3\0"+
    "\20\7\12\13\2\7\24\0\57\7\1\10\14\0\2\10\1\0\31\7"+
    "\10\0\120\7\2\10\45\0\11\7\2\0\147\7\2\0\4\7\1\0"+
    "\2\7\16\0\12\7\120\0\10\7\1\10\3\7\1\10\4\7\1\10"+
    "\27\7\5\10\20\0\1\7\7\0\64\7\14\0\2\10\62\7\21\10"+
    "\13\0\12\13\6\0\22\10\6\7\3\0\1\7\4\0\12\13\34\7"+
    "\10\10\2\0\27\7\15\10\14\0\35\7\3\0\4\10\57\7\16\10"+
    "\16\0\1\7\12\13\46\0\51\7\16\10\11\0\3\7\1\10\10\7"+
    "\2\10\2\0\12\13\6\0\27\7\3\0\1\7\1\10\4\0\60\7"+
    "\1\10\1\7\3\10\2\7\2\10\5\7\2\10\1\7\1\10\1\7"+
    "\30\0\3\7\43\0\6\7\2\0\6\7\2\0\6\7\11\0\7\7"+
    "\1\0\7\7\221\0\43\7\10\10\1\0\2\10\2\0\12\13\6\0"+
    "\u2ba4\7\14\0\27\7\4\0\61\7\u2104\0\u012e\7\2\0\76\7\2\0"+
    "\152\7\46\0\7\7\14\0\5\7\5\0\1\7\1\10\12\7\1\0"+
    "\15\7\1\0\5\7\1\0\1\7\1\0\2\7\1\0\2\7\1\0"+
    "\154\7\41\0\u016b\7\22\0\100\7\2\0\66\7\50\0\15\7\3\0"+
    "\20\10\20\0\7\10\14\0\2\7\30\0\3\7\31\0\1\7\6\0"+
    "\5\7\1\0\207\7\2\0\1\10\4\0\1\7\13\0\12\13\7\0"+
    "\32\7\4\0\1\7\1\0\32\7\13\0\131\7\3\0\6\7\2\0"+
    "\6\7\2\0\6\7\2\0\3\7\3\0\2\7\3\0\2\7\22\0"+
    "\3\10\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\2\3\2\1\1\4\1\1"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\16\3\1\21\1\22\1\0"+
    "\2\3\2\0\1\23\3\0\1\4\31\3\1\22\1\3"+
    "\1\0\1\24\1\0\13\3\1\25\5\3\1\26\1\3"+
    "\1\27\5\3\1\22\1\3\2\0\1\24\4\3\1\30"+
    "\1\3\1\31\1\32\4\3\1\33\11\3\1\34\2\0"+
    "\2\3\1\35\3\3\1\36\1\3\1\37\4\3\1\40"+
    "\1\41\1\42\1\3\1\43\1\0\1\3\1\44\1\45"+
    "\1\46\2\3\1\47\1\50\1\51\1\52\1\3\1\0"+
    "\2\3\1\53\1\54\1\23\1\55\1\3\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\u0212\0\65\0\65\0\65\0\65\0\65"+
    "\0\65\0\65\0\65\0\65\0\65\0\65\0\65\0\u0247"+
    "\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef"+
    "\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\324"+
    "\0\65\0\u0597\0\u0173\0\u05cc\0\65\0\u0212\0\u0601\0\u0636"+
    "\0\u066b\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de"+
    "\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986"+
    "\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e"+
    "\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6"+
    "\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e"+
    "\0\u0eb3\0\u0ee8\0\u0109\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1"+
    "\0\u0109\0\u1026\0\u0109\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f"+
    "\0\65\0\u1164\0\u1199\0\u11ce\0\u0ca1\0\u1203\0\u1238\0\u126d"+
    "\0\u12a2\0\u0109\0\u12d7\0\u0109\0\u0109\0\u130c\0\u1341\0\u1376"+
    "\0\u13ab\0\u0109\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4\0\u14e9"+
    "\0\u151e\0\u1553\0\u1588\0\u0109\0\u15bd\0\u15f2\0\u1627\0\u165c"+
    "\0\u0109\0\u1691\0\u16c6\0\u16fb\0\u0109\0\u1730\0\u0109\0\u1765"+
    "\0\u179a\0\u17cf\0\u1804\0\u0109\0\u0109\0\u0109\0\u1839\0\u0109"+
    "\0\u186e\0\u18a3\0\u0109\0\u0109\0\u0109\0\u18d8\0\u190d\0\u0109"+
    "\0\u0109\0\u0109\0\u0109\0\u1942\0\u1977\0\u19ac\0\u19e1\0\u0109"+
    "\0\u0109\0\u0173\0\u0109\0\u1a16\0\u0109";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\2\1\5\1\6\2\2\1\6"+
    "\2\2\1\7\1\10\1\11\1\12\1\13\1\2\1\6"+
    "\1\2\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\6\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\6\1\44\4\6\1\45\66\0\3\3"+
    "\65\0\1\46\1\47\57\0\6\50\1\51\56\50\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\24\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\6\6\1\52"+
    "\15\6\1\53\2\0\11\53\1\54\1\53\1\55\46\53"+
    "\20\0\1\12\1\56\65\0\1\57\1\60\26\0\1\60"+
    "\25\0\1\61\4\0\2\61\52\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\1\6"+
    "\1\62\22\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\11\6\1\63\12\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\1\6\1\64\4\6\1\65\15\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\1\6\1\66\13\6\1\67\6\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\2\6\1\70\21\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\71\2\0\2\6\1\0\1\6"+
    "\15\0\7\6\1\72\14\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\1\6"+
    "\1\73\3\6\1\74\16\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\7\6"+
    "\1\75\14\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\1\6\1\76\4\6"+
    "\1\77\15\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\3\6\1\100\1\101"+
    "\17\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\2\6\1\102\21\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\6\6\1\103\1\6\1\104\2\6\1\105"+
    "\10\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\5\6\1\106\1\6\1\107"+
    "\4\6\1\110\7\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\2\6\1\111"+
    "\16\6\1\112\2\6\2\46\1\0\62\46\5\47\1\113"+
    "\57\47\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\14\6\1\114\7\6\15\53"+
    "\1\115\47\53\13\0\1\116\4\0\2\116\62\0\1\117"+
    "\4\0\1\117\53\0\1\61\4\0\2\61\1\57\1\60"+
    "\26\0\1\60\21\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\2\6\1\120\21\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\4\6\1\121\17\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\13\6\1\122\10\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\11\6"+
    "\1\123\12\6\7\0\2\6\1\0\2\6\1\0\1\124"+
    "\2\0\2\6\1\0\1\6\15\0\24\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\1\6\1\125\22\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\6\6"+
    "\1\126\15\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\5\6\1\127\16\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\10\6\1\130\13\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\1\6\1\131\22\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\14\6"+
    "\1\132\7\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\1\133\23\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\1\6\1\134\22\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\135\2\0\2\6\1\0\1\6\15\0"+
    "\24\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\1\6\1\136\22\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\15\6\1\137\6\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\140\2\0\2\6\1\0\1\6\15\0"+
    "\24\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\3\6\1\141\20\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\1\142\23\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\5\6"+
    "\1\143\16\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\2\6\1\144\21\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\5\6\1\145\16\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\17\6\1\146\4\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\2\6"+
    "\1\147\21\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\3\6\1\150\20\6"+
    "\4\47\1\151\1\113\57\47\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\2\6"+
    "\1\152\21\6\1\53\2\0\3\53\1\153\2\53\3\153"+
    "\1\154\1\53\1\55\1\53\2\153\1\53\1\153\5\53"+
    "\2\153\12\53\1\153\2\53\1\153\1\53\1\153\1\53"+
    "\1\153\2\53\1\153\4\53\1\153\13\0\1\116\4\0"+
    "\2\116\1\0\1\60\26\0\1\60\25\0\1\155\4\0"+
    "\2\155\52\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\3\6\1\156\20\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\2\6\1\157\21\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\15\0"+
    "\11\6\1\160\12\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\20\6\1\161"+
    "\3\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\11\6\1\162\12\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\2\6\1\163\21\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\15\0"+
    "\22\6\1\164\1\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\5\6\1\165"+
    "\16\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\11\6\1\166\12\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\7\6\1\167\14\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\15\0"+
    "\7\6\1\170\14\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\2\6\1\171"+
    "\21\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\10\6\1\172\13\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\14\6\1\173\7\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\15\0"+
    "\11\6\1\174\12\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\23\6\1\175"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\2\6\1\176\21\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\7\6\1\177\14\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\12\6"+
    "\1\200\11\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\11\6\1\201\12\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\5\6\1\202\16\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\11\6\1\203\12\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\6\6"+
    "\1\204\15\6\1\53\2\0\3\53\1\205\2\53\3\205"+
    "\1\206\1\53\1\55\1\53\2\205\1\53\1\205\5\53"+
    "\2\205\12\53\1\205\2\53\1\205\1\53\1\205\1\53"+
    "\1\205\2\53\1\205\4\53\1\205\6\53\1\205\2\53"+
    "\4\205\1\115\2\53\2\205\1\53\1\205\5\53\2\205"+
    "\12\53\1\205\2\53\1\205\1\53\1\205\1\53\1\205"+
    "\2\53\1\205\4\53\1\205\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\2\6"+
    "\1\207\21\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\1\6\1\210\22\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\1\6\1\211\22\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\7\6\1\212\14\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\20\6"+
    "\1\213\3\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\12\6\1\214\11\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\21\6\1\215\2\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\12\6\1\216\11\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\1\6"+
    "\1\217\22\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\6\6\1\220\15\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\10\6\1\221\13\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\5\6\1\222\16\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\1\6"+
    "\1\223\22\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\3\6\1\224\20\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\11\6\1\225\12\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\13\6\1\226\10\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\11\6"+
    "\1\227\12\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\12\6\1\230\11\6"+
    "\1\53\2\0\3\53\1\231\2\53\3\231\1\54\1\53"+
    "\1\55\1\53\2\231\1\53\1\231\5\53\2\231\12\53"+
    "\1\231\2\53\1\231\1\53\1\231\1\53\1\231\2\53"+
    "\1\231\4\53\1\231\6\53\1\231\2\53\4\231\1\115"+
    "\2\53\2\231\1\53\1\231\5\53\2\231\12\53\1\231"+
    "\2\53\1\231\1\53\1\231\1\53\1\231\2\53\1\231"+
    "\4\53\1\231\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\4\6\1\232\17\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\13\6\1\233\10\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\21\6\1\234\2\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\12\6"+
    "\1\235\11\6\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\1\236\23\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\11\6\1\237\12\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\15\0"+
    "\22\6\1\240\1\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\7\6\1\241"+
    "\14\6\7\0\2\6\1\0\2\6\1\0\1\6\2\0"+
    "\2\6\1\0\1\6\15\0\11\6\1\242\12\6\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\3\6\1\243\20\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\15\0"+
    "\7\6\1\244\14\6\1\53\2\0\11\53\1\245\1\53"+
    "\1\55\46\53\7\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\15\0\2\6\1\246\21\6"+
    "\7\0\2\6\1\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\15\0\7\6\1\247\14\6\7\0\2\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\15\0\12\6\1\250\11\6\7\0\2\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\15\0\6\6"+
    "\1\251\15\6\14\53\1\245\1\115\1\252\46\53\7\0"+
    "\2\6\1\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\15\0\5\6\1\253\16\6\7\0\2\6\1\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\15\0"+
    "\4\6\1\254\17\6\7\0\2\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\15\0\11\6\1\255"+
    "\12\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6731];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\11\1\14\11\20\1\1\0\1\11\1\1"+
    "\2\0\1\11\3\0\34\1\1\0\1\1\1\0\31\1"+
    "\1\11\1\1\2\0\30\1\2\0\22\1\1\0\13\1"+
    "\1\0\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _AvroIdlLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _AvroIdlLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2224) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 34: 
          { return FIXED;
          }
        case 47: break;
        case 35: 
          { return BYTES;
          }
        case 48: break;
        case 44: 
          { return BOOLEAN;
          }
        case 49: break;
        case 9: 
          { return LEFT_BRACKET;
          }
        case 50: break;
        case 30: 
          { return ARRAY;
          }
        case 51: break;
        case 15: 
          { return SEMICOLON;
          }
        case 52: break;
        case 38: 
          { return THROWS;
          }
        case 53: break;
        case 46: 
          { return NAMESPACE;
          }
        case 54: break;
        case 36: 
          { return RECORD;
          }
        case 55: break;
        case 40: 
          { return SCHEMA;
          }
        case 56: break;
        case 23: 
          { return IDL;
          }
        case 57: break;
        case 33: 
          { return FALSE;
          }
        case 58: break;
        case 7: 
          { return LEFT_PAREN;
          }
        case 59: break;
        case 20: 
          { return FLOAT_LITERAL;
          }
        case 60: break;
        case 14: 
          { return COMMA;
          }
        case 61: break;
        case 13: 
          { return AT;
          }
        case 62: break;
        case 45: 
          { return PROTOCOL;
          }
        case 63: break;
        case 41: 
          { return DOUBLE;
          }
        case 64: break;
        case 29: 
          { return ORDER;
          }
        case 65: break;
        case 19: 
          { return STRING_LITERAL;
          }
        case 66: break;
        case 16: 
          { return EQUALS;
          }
        case 67: break;
        case 26: 
          { return NULL;
          }
        case 68: break;
        case 18: 
          { return BLOCK_COMMENT;
          }
        case 69: break;
        case 42: 
          { return IMPORT;
          }
        case 70: break;
        case 43: 
          { return ALIASES;
          }
        case 71: break;
        case 22: 
          { return INT;
          }
        case 72: break;
        case 5: 
          { return LEFT_BRACE;
          }
        case 73: break;
        case 11: 
          { return LEFT_ANGLE;
          }
        case 74: break;
        case 17: 
          { return LINE_COMMENT;
          }
        case 75: break;
        case 8: 
          { return RIGHT_PAREN;
          }
        case 76: break;
        case 37: 
          { return ONEWAY;
          }
        case 77: break;
        case 27: 
          { return ENUM;
          }
        case 78: break;
        case 32: 
          { return FLOAT;
          }
        case 79: break;
        case 10: 
          { return RIGHT_BRACKET;
          }
        case 80: break;
        case 28: 
          { return UNION;
          }
        case 81: break;
        case 39: 
          { return STRING;
          }
        case 82: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 83: break;
        case 31: 
          { return ERROR;
          }
        case 84: break;
        case 24: 
          { return TRUE;
          }
        case 85: break;
        case 3: 
          { return IDENTIFIER;
          }
        case 86: break;
        case 4: 
          { return INT_LITERAL;
          }
        case 87: break;
        case 25: 
          { return LONG;
          }
        case 88: break;
        case 12: 
          { return RIGHT_ANGLE;
          }
        case 89: break;
        case 6: 
          { return RIGHT_BRACE;
          }
        case 90: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 91: break;
        case 21: 
          { return MAP;
          }
        case 92: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
